apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:alpine3.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: 123@admin
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_DB
          value: kube-news
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  type: ClusterIP
  selector:
    app: postgre
  ports:
  - port: 5432
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-news
  template:
    metadata:
      labels:
        app: kube-news
    spec:
      containers:
      - name: kube-news
        image: dknunes/kube-news:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: DB_PASSWORD
          value: 123@admin
        - name: DB_USERNAME
          value: admin
        - name: DB_DATABASE
          value: kube-news
        - name: DB_HOST
          value: "postgre"


---

apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  type: NodePort
  selector:
    app: kube-news
  ports:
  - port: 8082
    targetPort: 8080
    nodePort: 30001

